management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: info
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
info:
  app:
    name: @project.artifactId@
    description: Сервер дискавери
    version: @project.version@