management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8088}
  endpoints:
    web:
      exposure:
        include: info
server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
logging:
  level:
    ROOT: ${ROOT_LOGGING:INFO}
application:
  locale: ru
  feignservce:
    rest: otuslibraryrest
info:
  app:
    name: 1
    description: Сервер приложения
    version: 1
security:
  enabled: true
feign:
  hystrix:
    enabled: true